# Generated by Django 2.1.3 on 2018-11-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_infor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='uni_intro',
            field=models.TextField(default='정보없음'),
            preserve_default=False,
        ),
    ]
